site_name: "{{ cookiecutter.project_name }}"
site_url: "{{ cookiecutter.site_url }}"
site_description: "{{ cookiecutter.description }}"

repo_name: "{{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}"
repo_url: "{{ cookiecutter.repository }}"
edit_uri: "edit/{{ cookiecutter.branch }}/docs/"

copyright: "Copyright &copy; {{ cookiecutter.year }} {{ cookiecutter.author }}"

nav:
  - "Home": README.md
  - "Contributing": contributing.md
  - "Changelog": changelog.md
  - "Code of Conduct": code-of-conduct.md

theme:
  name: material
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: black
      accent: yellow
  icon:
    repo: fontawesome/brands/github

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - markdown_include.include:
      base_path: .
