site_name: "{{ cookiecutter.project_name }}"
site_url: "{{ cookiecutter.homepage }}"
site_description: "{{ cookiecutter.description }}"

repo_name: "{{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}"
repo_url: "{{ cookiecutter.repository }}"
edit_uri: "edit/{{ cookiecutter.branch }}/docs/"

copyright: "Copyright &copy; {{ cookiecutter.year }} {{ cookiecutter.author }}"

nav:
  - "Home": README.md
  - "Contributing": contributing.md
  - "Changelog": changelog.md
  - "Code of Conduct": code-of-conduct.md

theme:
  name: material
  language: en
  palette:
    primary: black
    accent: yellow

plugins:
  - search:
      lang: en

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - markdown_include.include:
      base_path: .
