name: Bump version

on:
  push:
    branches: [ {{ cookiecutter.branch }} ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: {% raw -%}${{ secrets.GITHUB_TOKEN }}{%- endraw %}
          fetch-depth: 0

      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          push: true
          github_token: {% raw -%}${{ secrets.GITHUB_TOKEN }}{%- endraw %}
