name: CI Tests/Lints

on:
  push:
    branches: [ {{ cookiecutter.branch }} ]
  pull_request:
    branches: [ {{ cookiecutter.branch }} ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: '{{ cookiecutter.python_version }}'

      - name: Install python dependencies
        run: make install-poetry install

      - name: Run linters
        run: make lint
{% if cookiecutter.use_docs == 'True' %}
      - name: Test docs
        run: make docs
{% endif %}
      - name: Run test
        run: make test
