name: CI

on:
  push:
    branches: [ {{ cookiecutter.branch }} ]
  pull_request:
    branches: [ {{ cookiecutter.branch }} ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '{{ cookiecutter.python_version }}'

      - name: Install python dependencies
        run: make install-poetry install

      - name: Run linters
        run: make lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['{{ cookiecutter.python_version }}']
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: {% raw -%}${{ matrix.version }}{%- endraw %}

      - name: Install python dependencies
        run: make install-poetry install

      - name: Run test
        run: make test
{% if cookiecutter.use_docs  %}
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '{{ cookiecutter.python_version }}'

      - name: Install python dependencies
        run: make install-poetry install-docs

      - name: Test docs
        run: make docs{% endif %}
