name: Github pages

on:
  push:
    branches: [ {{ cookiecutter.branch }} ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '{{ cookiecutter.python_version }}'

      - name: Install python dependencies
        run: make install-uv install-docs

      - name: Generate docs
        run: make docs

      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: {% raw -%}${{ secrets.GITHUB_TOKEN }}{%- endraw %}
          publish_dir: ./site
