name: Publish to PYPI

on:
  push:
    tags:
      - '*'
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: '{{ cookiecutter.python_version }}'

      - name: Install poetry
        run: make install-poetry

      - name: Publish package to pypi
        run: make publish
        env:
          pypi_username: {% raw -%}${{ secrets.PYPI_USERNAME }}{%- endraw %}
          pypi_password: {% raw -%}${{ secrets.PYPI_PASSWORD }}{%- endraw %}
