name: Publish to PYPI

on:
  push:
    tags:
      - '*'
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
{% if cookiecutter.task_runner == "poethepoet" %}
      - name: Install poetry and poethepoet
        run: pip install poetry poethepoet

      - name: Publish package to pypi
        run: poe publish {% raw -%}${{ secrets.PYPI_USERNAME }} ${{ secrets.PYPI_PASSWORD }}{%- endraw %}
{% elif cookiecutter.task_runner == "Makefile" %}
      - name: Install poetry
        run: make install-poetry

      - name: Publish package to pypi
        run: make publish
        env:
          pypi_username: {% raw -%}${{ secrets.PYPI_USERNAME }}{%- endraw %}
          pypi_password: {% raw -%}${{ secrets.PYPI_PASSWORD }}{%- endraw %}
{% endif %}
