site_name: "{{ cookiecutter.project_name }}"
site_url: "{{ cookiecutter.homepage }}"
site_description: "{{ cookiecutter.description }}"

repo_name: "{{ cookiecutter.project_slug }}"
repo_url: "{{ cookiecutter.repository }}"
edit_uri: "edit/{{ cookiecutter.branch }}/docs/"

copyright: "Copyright &copy; {{ cookiecutter.year }} {{ cookiecutter.author }}"

nav:
  - "Home": README.md

theme:
  name: material
  language: en
  palette:
    primary: black
    accent: yellow

plugins:
  - include-markdown
  - search:
      lang: en
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
      watch:
        - "{{ cookiecutter.project_slug }}"

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
